Hops 1596
hopshadoop/hops pull request #823
Opened 2020-10-19 14:37 UTC by berthoug

## Make sure there is no duplicate PR for this issue

* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added and passed (for bug fixes / features)
- [ ] HOPS JIRA issue has been opened for this PR
- [ ] All commits have been squashed down to a single commit
- [ ] The commit message has the following format: [HOPS-XXX] message

* **Post a link to the associated JIRA issue**
https://hopshadoop.atlassian.net/browse/HOPS-1596
https://hopshadoop.atlassian.net/browse/HOPS-1597

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Bug fix

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

2020-10-20 07:44 UTC, maismail requested changes

2020-10-20 07:44 UTC, maismail commented on hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/DecommissionManager.java
> +                    //The inode does not exist anymore.
We should add a debug message in here

2020-10-20 07:44 UTC, maismail commented on hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/blockmanagement/DecommissionManager.java
> +                    //The inode does not exist anymore.
Same as above

2020-10-20 08:21 UTC, maismail approved these changes

2020-10-29 12:06 UTC, berthoug commented
merged with  #822

2020-10-29 12:06 UTC, closed without merging